_("Filer windows")
_("Auto-resize filer windows")
_("Never automatically resize")
_("You'll have to resize windows manually, using the window manager, the `Resize Window' menu entry or by double-clicking on the window background.")
_("Resize when changing the display style")
_("Changing the size of the icons or which details are displayed will resize the window for you.")
_("Always resize")
_("The filer will resize windows whenever it seems useful (that is, when changing directory or display style).")
_("Largest window size:")
_("%")
_("The largest size, as a percentage of the screen size, that the auto-resizer will resize a window to.")
_("Largest window width:")
_("%")
_("The largest width, as a percentage of the screen size, that the auto-resizer will resize a window to.")
_("Window behaviour")
_("Short titlebar flags")
_("Use single letters instead of words for Scanning, All and Thumbs indicators in the titlebar.")
_("Unique windows")
_("If you open a directory and that directory is already displayed in another window, then this option causes the other window to be closed.")
_("Close window when dir missing")
_("If a directory that is open in a window disappears, (deleted or unmounted) automatically close window.")
_("Window Link")
_("If this is on and you open a directory by middle button, the new window and the source window are toggled into link mode. In link mode, left-click a directory to open it in a window placed to the right of the source window. If this value is off, ctrl + middle button toggles the linked window.")
_("New window on button 1")
_("Clicking with mouse button 1 (usually the left button) opens a directory in a new window with this turned on. Clicking with the button-2 (middle) will reuse the current window.")
_("Single-click navigation")
_("Clicking on an item opens it with this on. Hold down Control to select the item instead. If off, clicking once selects an item; double click to open things.")
_("Double-click on background resizes")
_("If on then double clicking on the window background resizes the window, just like clicking on the Automatic size mode button in the toolbar.")
_("Sorting")
_("Directories come first (for sort by name)")
_("If this is on then directories will always appear before anything else when sorting by name.")
_("Capitalised names first (for sort by name)")
_("If on, all filenames starting with a capital letter come before filenames starting with lowercase ones.")
_("Newly comes first (for sort by Date)")
_("If on, the Sort by Dates are reversed.")
_("etc")
_("Show extended attribute indicator")
_("If this is on then files which have one or more extended attributes set will have an emblem added to indicate this.")
_("Hide the message bar Running as user 'root'")
_("This hides the bar even with the command-line option -u, --user if user is the root.")
_("New Window")
_("Default settings for new windows")
_("Inherit options from source window")
_("If this is on then display options for a new window are inherited from the source window if possible, otherwise they are set to the defaults below.")
_("View type:")
_("Icons View")
_("List View")
_("Sort by:")
_("Name")
_("Type")
_("Date (m)")
_("Date (c)")
_("Date (a)")
_("Size")
_("Show hidden files")
_("If this is on then files whose names start with a dot are shown too, otherwise they are hidden.")
_("Huge Icons size:")
_("pixels")
_("Resolution depends on 'Thumbnails->Cache File Size'.")
_("Icon View")
_("Icon View")
_("Default size:")
_("Huge Icons")
_("Large Icons")
_("Small Icons")
_("Automatic")
_("Default details:")
_("No details")
_("Sizes")
_("Permissions")
_("Type")
_("Times")
_("Automatic small icons: Change at:")
_("items")
_("When automatic icon sizing is selected: If the directory contains this many items then it will be shown using Small Icons, otherwise Large Icons will be used.")
_("Large Icons: (Max width):")
_("pixels")
_("Text wider than this is broken onto two lines in Large Icons mode.")
_("(Wrapped, Details):")
_("pixels")
_("Maximum length for Large Icons mode and Details. This can be changed temporarily by right dragging of the toolbar.")
_("Wrap by characters")
_("If this option is on, file names will wrap by characters instead of words.")
_("Small Icons (Max width):")
_("pixels")
_("Maximum width for the text beside a Small Icon.")
_("Order small icons vertically")
_("If this option is on, then small icons are arranged in columns, not rows.")
_("Order large icons vertically")
_("If this option is on, then large icons are arranged in columns, not rows.")
_("Scroll speed: 1/")
_("view")
_("List View")
_("List View")
_("Show column headings")
_("If this is on then column headings will be shown in the list view.")
_("Show full type")
_("If this is on then the full description of each object's type will be show rather than a short summary of its basic type.")
_("Only icons and names are clickable")
_("For lasso.")
_("Save columns order")
_("If this is on reordering columns is saved")
_("Name column width (Max):")
_("pixels")
_("Maximum width for the Name Column.")
_("Show Columns")
_("Name")
_("If this is on then Name column will be shown in the list view.")
_("Type")
_("If this is on then Type column will be shown in the list view.")
_("Size")
_("If this is on then Size column will be shown in the list view.")
_("Permissions")
_("If this is on then Permissions column will be shown in the list view.")
_("Owner")
_("If this is on then Owner column will be shown in the list view.")
_("Group")
_("If this is on then Group column will be shown in the list view.")
_("Last Modified")
_("If this is on then Last Modified column will be shown in the list view.")
_("Last Changed")
_("If this is on then Last Changed column will be shown in the list view.")
_("Last Accessed")
_("If this is on then Last Accessed column will be shown in the list view.")
_("Tools/Minibuffer")
_("Toolbar")
_("Toolbar type:")
_("No toolbar")
_("Icons only")
_("Text under icons")
_("Text beside icons")
_("Text only")
_("Show totals of items")
_("Show the number of items displayed in a filer window, as well as the number of hidden items (if any). When there's a selection, show the number of selected items and their combined size.")
_("Select the buttons you want on the bar:")
_("Width of toolbar sets minimum width of window")
_("Each filer window is constrained to be wide enough to show the whole of the toolbar")
_("Minibuffer")
_("Beep if Tab-completion fails")
_("When using the `Enter Path...' minibuffer and Tab is pressed, beep if nothing happens (eg, because there are several possibilities and the next letter varies).")
_("Beep if there are several matches")
_("When using the `Enter Path...' minibuffer and Tab is pressed, beep if there is more than one matching file, even though some more letters were added.")
_("Stdout handler")
_("This will be run when Mini Shell puts out string to stdout. $1 is the string.")
_("Errout handler")
_("This will be run when Mini Shell puts out string to errout. $1 is the string.")
_("Thumbnails")
_("Thumbnails")
_("Show image thumbnails")
_("This is the default setting for new windows. Use the Display menu to turn thumbnails on and off for individual windows.")
_("Show image thumbnail for directory.")
_("When no items in a sub-directory have a thumbnail, this process tries to create a thumbnail. If you don't like the choice, visit the sub-directory and middle-click the scan button in the toolbar to choose the first item.")
_("Video Thumbnailer:")
_("Default generator For video/*.")
_("Thumbnails cache")
_("To speed things up, the generated thumbnails are stored in the hidden ~/.cache/literocks directory. Click here to remove the cached thumbnails. They will be created again as needed.")
_(" being left over ")
_("days")
_("0 is all.")
_("Cache File Size:")
_("Small (64px)")
_("Normal (128px)")
_("Large (256px)")
_("Huge (512px)")
_("Action windows")
_("Action windows appear when you start a background\noperation, such as copying or deleting some files.")
_("Auto-start (Quiet) these actions")
_("Copy")
_("Copy files without confirming first.")
_("Move")
_("Move files without confirming first.")
_("Link")
_("Create links to files without confirming first.")
_("Delete")
_("Delete files without confirming first.")
_("Mount")
_("Mount and unmount filesystems without confirming first.")
_("Default settings")
_("Force Del")
_("Don't confirm deletion of non-writeable items.")
_("Brief")
_("Don't display so much information in the message area.")
_("Recurse")
_("Also change contents of subdirectories.")
_("Merge")
_("Always merge directories.")
_("Newer")
_("Always over-write if source is newer than destination.")
_("Ignore Older")
_("Silently ignore if source is older than destination.")
_("Mount commands")
_("Mount command")
_("The command used to mount a filesystem. If unsure, use \"mount\".")
_("Unmount command")
_("The command used to unmount a filesystem. If unsure, use \"umount\" (yes, without the first \"n\").")
_("Eject command")
_("The command used to eject removable media. If unsure, use \"eject\".")
_("Wink")
_("Wink last move/copy/linked item")
_("Drag and Drop")
_("Dragging to icons")
_("Allow dragging to icons in filer windows")
_("When this is on you can drag a file over a sub-directory or program in a filer window. The item will highlight when you do this and dropping the file will put it into that directory, or load it into the program.")
_("Directories spring open")
_("This option, which requires the above option to be turned on too, causes the highlighted directory to 'spring open' after the file is held over it for a short while.")
_("Spring delay:")
_("ms")
_("This option sets how long, in ms, you must hold a file over a directory before it will spring open. The above option must be turned on for this to have any effect.")
_("When dragging files with the left mouse button")
_("Show a menu of possible actions")
_("Copy the files")
_("Note that you can still get the menu to appear, by dragging with Alt held down.")
_("When dragging files with the middle mouse button")
_("Show a menu of possible actions")
_("Move the files")
_("Note that you can still get the menu to appear, by dragging with the left button and holding down the Alt key.")
_("Download handler")
_("When you drag a file from a web browser or other remote source, this program will be run to download it. $1 is the URI dragged to the filer, and the current directory is the destination. Eg:\nxterm -e wget $1")
_("Menus")
_("Appearance")
_("Size of icons in menus:")
_("No Icons")
_("Small Icons")
_("Large Icons")
_("Same as current window")
_("Same as default")
_("Behaviour")
_("File menu on right-click")
_("Show the File menu instead of the main menu when right-clicking with files selected (the main menu can be accessed by holding down Control).")
_("Terminal emulator program")
_("The program to launch when you choose `Terminal Here' from the menu.")
_("Keyboard shortcuts")
_("Colours")
_("File type colours")
_("Colour files based on their types")
_("Filenames (and details) are coloured according to the file's type.")
_("Directory:")
_("Regular file:")
_("Pipe:")
_("Socket:")
_("Error:")
_("Error, such as a symlink which points to a non-existant file, or a file which the filer does not have permission to examine.")
_("Character device:")
_("Block device:")
_("Door:")
_("Door files are a bit like sockets or pipes, and have only been seen on Solaris.")
_("Executable file:")
_("Application directory:")
_("Unknown type:")
_("Background colour")
_("Use custom background colour:")
_("Transparency:")
_("%")
_("This depends on your environment. Basically if your windows have shadows, then they can also be transparent.")
_("Compatibility")
_("Command line program")
_("Make script")
_("Drag and drop")
_("Don't use hostnames")
_("Some older applications don't support XDND fully and may need to have this option turned on. Use this if dragging files to an application shows a + sign on the pointer but the drop doesn't work.")
_("etc")
_("Fast width calculating")
_("If this is on, string width calculations will be faster but less accurate in Small Icons mode.")
_("Purge Dir Cache")
_("Don't check this if you haven't problems with RAM.")
_("Take control of window move on auto-resize")
_("When this is on, rox rather than the window manager, handles window move. When this is off, pointer warp on auto-move is disabled.")
_("Bottom gap:")
_("pixels")
_("For the overridden auto-move in the auto-resize and the display settings.")
_("Right gap:")
_("pixels")
_("For the overridden auto-move in the auto-resize and the display settings.")
_("Disable pointer warp")
_("Check this if you don't want your mouse pointer to be moved on window shrink/auto-move.")
